### ISSUE TITLE
Unable to get docker image to work anymore

### ISSUE THREAD

**Issue by Sir-Will** [wbbaddons/Tims-PackageServer#34]
Hey,

I was trying to install the docker image on a new server and was no longer able to get it to work. 
`curl -I http://localhost:9001` just returns `HTTP/1.1 405 Method Not Allowed` and docker logs doesn't show anything, so not sure how to troubleshoot this further without any log results.

Installation process:
```
git clone https://github.com/wbbaddons/Tims-PackageServer.git
cd Tims-PackageServer/
docker-compose up --build -d
curl -I http://localhost:9001
```
Tims-PackageServer/docker-compose.yaml
````yml
version: "3"

services:
  packageserver:
    build: .
    restart: always
    ports:
      - "9001:9001"
    environment:
      DEBUG: "PackageServer:*"
    volumes:
      - /srv/docker/packageserver/packages:/var/lib/PackageServer/packages
````
