### ISSUE TITLE
Docker: version `GLIBC_2.34' not found (required by tims-package-server)

### ISSUE THREAD

**Issue by Sir-Will** [wbbaddons/Tims-PackageServer#381]
After trying to install the package server on a new server, I'm facing the issue of it throwing the error below.
The base image `debian:bookworm-slim` seems to have 2.36, so I don't understand why it's looking for 2.34 and 2.32 here.

> /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by tims-package-server)
>
>  /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by tims-package-server)

Any idea what the issue could be here?

**Comment by TimWolla** [comment]
You will need to provide some more detail as to how exactly you're running it.

**Comment by Sir-Will** [comment]
I'm using the latest changes from this repo, via a simple git clone:

- git clone of this repo.
- `docker-compose.yaml` file created in the cloned repo
```yml
services:
  packageserver:
    build: .
    restart: always
    ports:
      - "9001:9001"
    environment:
      DEBUG: "PackageServer:*"
    volumes:
      - /srv/docker/packageserver/packages:/var/lib/PackageServer/packages
```
- `docker compose up`
